package uk.q3c.kaytee.agent.system

import uk.q3c.kaytee.agent.build.Build
import java.io.File

/**
 * The directory structure fora build is:<br>
 *
 *     <dataDir>/<projectDir>/<buildNumberDir>/<projectInstanceDir>
 *
 * for example:
 *
 *     ~/kaytee-data/kaytee-test/99/kaytee-test
 *
 *
 *
 * Created by David Sowerby on 08 Jan 2017
 */
interface InstallationInfo {

    /**
     * The directory KayTee is installed in
     */
    var installDirRoot: File

    /**
     * the directory used for holding KayTee working data
     */
    var dataDirRoot: File


    /**
     * The directory to be used by the project within the [dataDirRoot], for example /user/home/kaytee-data/krail
     *
     * Only one directory is used per project.
     *
     * @param build the build associated with this specific build for this project
     *
     * @return The directory to be used for the project build.
     */
    fun projectDir(build: Build): File

    /**
     * The directory containing project directory
     */
    fun buildNumberDir(build: Build): File

    /**
     * File containing [stdout] generated by Gradle during a build
     */
    fun gradleStdErrFile(build: Build): File

    /**
     * File containing [stderr] generated by Gradle during a build
     */
    fun gradleStdOutFile(build: Build): File

    /**
     * Directory to hold [gradleStdErrFile] and [gradleStdOutFile] files.  These are in a separate directory to
     * the [projectDir], to avoid being deleted by a 'clean' ope
     */
    fun gradleOutputDir(build: Build): File

    fun dataDir(): File
    fun installDir(): File
    fun projectInstanceDir(build: Build): File
}